
DROP DATABASE IF EXISTS MyDB;
CREATE DATABASE MyDB;
use MyDB;
CREATE TABLE users(
id INTEGER PRIMARY KEY  AUTO_INCREMENT,
login VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE groups(
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL
);

CREATE TABLE users_groups(
user_id INTEGER REFERENCES users(id)
 ON UPDATE CASCADE
 ON DELETE CASCADE,
group_id INTEGER REFERENCES groups(id)
ON UPDATE CASCADE
 ON DELETE CASCADE
);
INSERT INTO users VALUES(DEFAULT, 'ivanov');


INSERT INTO groups VALUES(DEFAULT, 'teamA');


SELECT * FROM users;

SELECT * FROM groups;
